### ISSUE TITLE
Your Vision

### ISSUE THREAD

**Issue by LupusOssorum** [Devisualization/spew#1]
Hi, if you can spare your time.

I just ran into this.  I may have interest in this, and may offer my aid.

I have been working on building D libraries for Graphics and Window/Event handling (Not for very long, mostly experimental beginnings of execution).  But if your vision and mine are compatible, joining with you would be more time effective.

Thanks,
Jonathan

**Comment by rikkimax** [comment]
SPEW is my third iteration towards a windowing library. There are a lot of lessons learned in it.

1) A very powerful event loop abstraction + implementation (GUI toolkit versus game versus VST plugin versus web server)
2) Each platform may offer a feature, but you quite often won't know until runtime and most of the time you don't care
3) You may think that sockets and a window have nothing in common, except it does, same with timers quite a lot actually (event loop)

Pretty much all design decisions have been based off of this.

[de_window](https://github.com/devisualization/window) was the last iteration. All three of my above points are not covered here.

**Comment by LupusOssorum** [comment]
Cool, do you think you finally have nailed it were it should be...? 

3 general target questions.

~What is your use target?  Do you intend to make this library broad enough to be able to be used for a GUI applications (as opposed to just games) and Visa Versa.~ This one should have been obvious...  

~Does your design allow directly talking with a OpenGL?~ Same with this one. I misread your remark at the bottom of the README.

Will this handle outlandish system events like a parallel to SDL's "Text Editing" event.  (I think you touched on this in your first point...)

**Comment by rikkimax** [comment]
Without signatures the design is as good as I'll get it I think.

My target is: "GUI toolkit versus game versus VST plugin versus web server" each one of these has a very different event loop handling and they are all covered.

I don't have any OpenGL bindings that I suggest that you use. I do have a [rather large one](https://github.com/Devisualization/bindings/tree/master/source/opengl/devisualization/bindings/opengl) that I generate from my program [ogl_gen](https://github.com/rikkimax/ogl_gen).

However its just a matter of filling out a [struct](https://github.com/Devisualization/spew/blob/master/src/base/cf/spew/ui/context/features/opengl.d#L23) to my own OpenGL context and it'll just work [example1](https://github.com/Devisualization/bindings/blob/master/source/opengl/devisualization/bindings/opengl/loader.d) [example2](https://github.com/Devisualization/spew/blob/master/src/diagnostic.d#L394).

The OpenGL bindings I do offer that was generated is very slow to load + compile and causes an ICE with dmd (size limit), OpenGL is big at > 5000 functions now.

But if my context isn't good enough (which is common for say AAA games) you can implement a [custom](https://github.com/Devisualization/spew/blob/master/src/base/cf/spew/ui/context/features/custom.d) one and assign that. Which is good because currently we don't have DirectX binding and so I'm not offering an implementation for that (or a lot of them really).

Can you please link the event for SDL that you mean? I suspect I know what it is and the answer is both yes possible and no not implemented.

**Comment by LupusOssorum** [comment]
Oh, I see what you meant by "GUI toolkit versus game versus VST plugin versus web server" now, thanks for the clarification.

The fact that you do not implement OpenGL binding in this library I agree with.  (Let the user do graphics how they want)

So, this rather similar to SDL?  What are the differences?  I know SDL has some build it Graphics handing and it looks like this does not (a good thing I think).

The "Text Editing" event thing.  "https://wiki.libsdl.org/Tutorials/TextInput"

**Comment by rikkimax** [comment]
SDL covers a lot more, it is a multimedia library. SPEW is a windowing library its job is to abstract as much as possible over the system libraries. You should be able to implement SDL on top of it.

glfw would be a better comparison than SDL is.

The SDL text input stuff is because they tacked on Unicode support. That's already included in the key input side of things. [example1](https://github.com/Devisualization/spew/blob/master/src/base/cf/spew/ui/events.d#L36) [example2](https://github.com/Devisualization/spew/blob/master/src/diagnostic.d#L437)

Notice how it takes a dchar and not a char? (The diagnostic module is meant to cover the entire API for both testing and verification purpose but also to serve as examples).

**Comment by LupusOssorum** [comment]
Wow.

I am digging through "diagnostic.d" now...

I am a big fan of modularizing code.  Build things in small pieces that way each piece is as small as it can get.  (Your statement "You should be able to implement SDL on top of it." is akin.)  

> Notice how it takes a dchar and not a char? (The diagnostic module is meant to cover the entire API for both testing and verification purpose but also to serve as examples).

Good,

**Comment by LupusOssorum** [comment]
Do you have plans to extend implementation to Mobile (Android, iOS, Windows Metro)?

**Comment by rikkimax** [comment]
API is designed for it, (see IRenderPoint versus IWindow, this also covers consoles), but I doubt I'll be the one implementing it. Mobile is a real pain, just like consoles.

**Comment by LupusOssorum** [comment]
What is your `cf` namespace?  Why `cf.spew...` not just `spew...`.

**Comment by LupusOssorum** [comment]
I like how you use cuddly braces... and tabs...

You should try Elastic Tab-stops (http://nickgravgaard.com/elastic-tabstops/)
